### ISSUE TITLE
Mailcatcher

### ISSUE THREAD

**Issue by jonasdt** [diogoosorio/zidisha-vagrant#1]
One nice way of dealing with mail during development is [MailCatcher](http://mailcatcher.me/). After installation, you have to set `define("PHP_EMAILS", true);` in `library/constant.php` and it will work. Would you like to add this to the ansible provisioning?

These instructions will get you started https://gist.github.com/FrenkyNet/8234108.

Thanks again!

**Comment by diogoosorio** [comment]
Sure, this seems trivial. There's even a community written role to tackle this challenge.

https://github.com/perlmonkey/role-mailcatcher

I'll implement this tomorrow. :+1:

**Comment by diogoosorio** [comment]
I've just merged it into the master branch (via a3cbd8f8928253766d4beb566927c82c0a76884e).
